import imghdr
import subprocess
import sys, os

from PyQt5 import QtWidgets, QtCore
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog, QMessageBox


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(736, 510)
        dialog.setSizeGripEnabled(False)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dialog)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(dialog)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Image = QtWidgets.QWidget()
        self.Image.setObjectName("Image")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Image)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 601, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(6, 8, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_Input = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_Input.setObjectName("lbl_Input")
        self.verticalLayout.addWidget(self.lbl_Input)
        self.le_Input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_Input.sizePolicy().hasHeightForWidth())
        self.le_Input.setSizePolicy(sizePolicy)
        self.le_Input.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.le_Input.setObjectName("le_Input")
        self.verticalLayout.addWidget(self.le_Input)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_Output = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_Output.setObjectName("lbl_Output")
        self.verticalLayout_2.addWidget(self.lbl_Output)
        self.le_Output = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_Output.sizePolicy().hasHeightForWidth())
        self.le_Output.setSizePolicy(sizePolicy)
        self.le_Output.setObjectName("le_Output")
        self.verticalLayout_2.addWidget(self.le_Output)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.btn_OpenInput = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_OpenInput.sizePolicy().hasHeightForWidth())
        self.btn_OpenInput.setSizePolicy(sizePolicy)
        self.btn_OpenInput.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.btn_OpenInput.setObjectName("btn_OpenInput")
        self.verticalLayout_4.addWidget(self.btn_OpenInput)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.btn_OpenOutput = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_OpenOutput.sizePolicy().hasHeightForWidth())
        self.btn_OpenOutput.setSizePolicy(sizePolicy)
        self.btn_OpenOutput.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.btn_OpenOutput.setObjectName("btn_OpenOutput")
        self.verticalLayout_5.addWidget(self.btn_OpenOutput)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.btn_Apply = QtWidgets.QDialogButtonBox(self.Image)
        self.btn_Apply.setGeometry(QtCore.QRect(639, 430, 81, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Apply.sizePolicy().hasHeightForWidth())
        self.btn_Apply.setSizePolicy(sizePolicy)
        self.btn_Apply.setOrientation(QtCore.Qt.Horizontal)
        self.btn_Apply.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
        self.btn_Apply.setCenterButtons(False)
        self.btn_Apply.setObjectName("btn_Apply")
        self.progressBar = QtWidgets.QProgressBar(self.Image)
        self.progressBar.setGeometry(QtCore.QRect(350, 430, 274, 25))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Image)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 160, 371, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_filters = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_filters.sizePolicy().hasHeightForWidth())
        self.cb_filters.setSizePolicy(sizePolicy)
        self.cb_filters.setObjectName("cb_filters")
        self.horizontalLayout_2.addWidget(self.cb_filters)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cb_Resize = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_Resize.sizePolicy().hasHeightForWidth())
        self.cb_Resize.setSizePolicy(sizePolicy)
        self.cb_Resize.setObjectName("cb_Resize")
        self.gridLayout_2.addWidget(self.cb_Resize, 0, 0, 1, 1)
        self.le_ResizeY = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ResizeY.sizePolicy().hasHeightForWidth())
        self.le_ResizeY.setSizePolicy(sizePolicy)
        self.le_ResizeY.setObjectName("le_ResizeY")
        self.gridLayout_2.addWidget(self.le_ResizeY, 2, 2, 1, 1)
        self.le_ResizeX = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_ResizeX.sizePolicy().hasHeightForWidth())
        self.le_ResizeX.setSizePolicy(sizePolicy)
        self.le_ResizeX.setObjectName("le_ResizeX")
        self.gridLayout_2.addWidget(self.le_ResizeX, 1, 2, 1, 1)
        self.lbl_X = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_X.sizePolicy().hasHeightForWidth())
        self.lbl_X.setSizePolicy(sizePolicy)
        self.lbl_X.setObjectName("lbl_X")
        self.gridLayout_2.addWidget(self.lbl_X, 1, 1, 1, 1)
        self.lbl_Y = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Y.sizePolicy().hasHeightForWidth())
        self.lbl_Y.setSizePolicy(sizePolicy)
        self.lbl_Y.setObjectName("lbl_Y")
        self.gridLayout_2.addWidget(self.lbl_Y, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.Image, "Image")
        self.Video = QtWidgets.QWidget()
        self.Video.setObjectName("Video")
        self.tabWidget.addTab(self.Video, "VIdeo")
        self.Virt = QtWidgets.QWidget()
        self.Virt.setObjectName("Virt")
        self.tabWidget.addTab(self.Virt, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Project"))
        self.lbl_Input.setText(_translate("dialog", "Path to input file"))
        self.lbl_Output.setText(_translate("dialog", "Path to output file"))
        self.cb_filters.setText(_translate("dialog", "filters"))
        self.cb_Resize.setText(_translate("dialog", "Resize"))
        self.lbl_X.setText(_translate("dialog", "X:"))
        self.lbl_Y.setText(_translate("dialog", "Y:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Virt), _translate("dialog", "Virtual Camera"))


class MainWindow(QDialog, Ui_dialog):
    def __init__(self):
        super().__init__()
        self.msg = QMessageBox()
        self.msg.setWindowTitle("Error")
        self.msg.setIcon(QMessageBox.Critical)
        self.inType = None
        self.outPath = ""
        self.inPath = ""
        self.setupUi(self)
        self.btn_Apply.clicked.connect(self.Apply)
        self.btn_OpenInput.clicked.connect(self.Input)
        self.btn_OpenOutput.clicked.connect(self.Output)
        self.cb_filters.clicked.connect(self.FilterCheck)

    def Refresh(self):
        self.inPath = self.le_Input.text()
        self.outPath = self.le_Output.text()

    def Apply(self):
        self.Refresh()
        if os.path.exists(self.inPath):
            if self.inType is not None:
                # os.system(f"ffmpeg -i {self.inPath} {self.outPath}")      decided to use subprocess instead
                with open(os.devnull, 'wb') as devnull:
                    subprocess.check_call(['/usr/local/bin/ffmpeg', '-i', self.inPath, self.outPath], stdout=devnull,
                                          stderr=subprocess.STDOUT)
            else:
                self.msg.setText("Please input path to your IMAGE file.")
                self.msg.exec_()
        else:
            self.msg.setText("Incorrect path(s)")
            self.msg.exec_()

    def Input(self):
        try:
            self.inPath, ok = QFileDialog.getOpenFileName(self, "Choose image", '')
            self.inType = imghdr.what(self.inPath)
            if ok:
                if self.inType is not None:
                    self.le_Input.setText(self.inPath)
        except FileNotFoundError:
            self.msg.setText("File Not Found")
            self.msg.exec_()

    def Output(self):
        self.outPath, ok = QFileDialog.getSaveFileName(self, "Choose image", '')
        if ok:
            self.le_Output.setText(self.outPath)

    def FilterCheck(self):
        if self.cb_filters.isChecked():
            print("filters checked")
        else:
            print("filters unchecked")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    mw = MainWindow()
    mw.show()
    sys.exit(app.exec_())
